// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzXQ7rVakcR8i4LBmL01CZuGLSdrU4TqA',
    appId: '1:570523249460:web:7ed83f2e00a2c881d21361',
    messagingSenderId: '570523249460',
    projectId: 'task-bdb4a',
    authDomain: 'task-bdb4a.firebaseapp.com',
    storageBucket: 'task-bdb4a.appspot.com',
    measurementId: 'G-19Z99TF7XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqXLhdfkdmup5yEfzQNM_f1F7lP_pz3U',
    appId: '1:570523249460:android:7f67f6661e98d8dbd21361',
    messagingSenderId: '570523249460',
    projectId: 'task-bdb4a',
    storageBucket: 'task-bdb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDczHqPFI2mVHqpL9opwTKOsIqyje5rvL8',
    appId: '1:570523249460:ios:d0f49db635991341d21361',
    messagingSenderId: '570523249460',
    projectId: 'task-bdb4a',
    storageBucket: 'task-bdb4a.appspot.com',
    iosClientId: '570523249460-urdfdd7vg66f0q290uu600a8f4q6q8te.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDczHqPFI2mVHqpL9opwTKOsIqyje5rvL8',
    appId: '1:570523249460:ios:d0f49db635991341d21361',
    messagingSenderId: '570523249460',
    projectId: 'task-bdb4a',
    storageBucket: 'task-bdb4a.appspot.com',
    iosClientId: '570523249460-urdfdd7vg66f0q290uu600a8f4q6q8te.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
